version: '3.3'

services:
  dp:
    container_name: database
    image: sameersbn/postgresql:10-2
    environment:
      PG_PASSWORD: $PG_PASSWORD
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./pgdata:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python bot.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    depends_on:
      - db
  networks:
    botnet:
      driver: bridge
