version: '3.3'

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    environment:
      PG_PASSWORD: $PG_PASSWORD
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgresql:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python bot.py
    volumes:
      - .:/src
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    depends_on:
      - db
      - django
  django:
    container_name: djangoproject
      build:
        context: .
      command: python django_app.py runserver 0.0.0.0:8000 --noreload
      ports:
        - 8000:8000
      networks:
        - botnet
      restart: always

      volumes:
        - .:/src
      env_file:
        - ".env"
      # Бот стартует после запуска базы
      depends_on:
        - db

  networks:
    botnet:
      driver: bridge
