# Generated by Django 4.0.5 on 2022-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='receiver',
            field=models.CharField(max_length=100, null=True, verbose_name='Receiver name'),
        ),
    ]
