# Generated by Django 4.0.5 on 2022-06-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_admin', '0003_rename_name_user_username_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='Username Telegram'),
        ),
    ]
